In [1]:
import numpy as np

In [3]:
s = np.array([2])

In [4]:
type(s)

numpy.ndarray

In [17]:
v = np.array([1,-3,245])

In [6]:
v

array([  1,  -3, 245])

In [8]:
v.shape

(3,)

In [9]:
s.shape

(1,)

In [10]:
v.reshape

<function ndarray.reshape>

In [18]:
v.shape

(3,)

In [24]:
v = v.reshape(3,1)

In [25]:
v

array([[  1],
       [ -3],
       [245]])

In [27]:
np.array([[  1,  -3, 245],[  0,  -2, 246]])

array([[  1,  -3, 245],
       [  0,  -2, 246]])

### Tensor

In [29]:
np.array([[[  1,  -3, 245],[  0,  -2, 246]],[[  1,  3, 2],[  3,  49, 77]]])

array([[[  1,  -3, 245],
        [  0,  -2, 246]],

       [[  1,   3,   2],
        [  3,  49,  77]]])

In [48]:
m1 = np.array([[  1,  -3, 245],[  0,  -2, 246]])
m2 = np.array([[  1,  3, 2],[  3,  49, 77]])

In [49]:
m1 * m2

array([[    1,    -9,   490],
       [    0,   -98, 18942]])

In [51]:
v1 = np.array([3,4,5])

In [52]:
v1.shape

(3,)

In [53]:
v1.T

array([3, 4, 5])

In [59]:
v1 = v1.reshape(1,3)
v1

array([[3, 4, 5]])

In [60]:
v1.shape

(1, 3)

In [61]:
v1.T

array([[3],
       [4],
       [5]])

In [72]:
d1 = {'name':'Jay','age': 27,'education':'masters'}

In [77]:
d1.values()

dict_values(['Jay', 27, 'masters', 100000])

In [75]:
d2 = {'salary': 100000}

In [78]:
d1

{'name': 'Jay', 'age': 27, 'education': 'masters', 'salary': 100000}

In [79]:
### Pandas

In [80]:
import pandas as pd

In [89]:
pd.Series(np.array([1,2,3,4]))

0    1
1    2
2    3
3    4
dtype: int64

In [95]:
pd.Series(range(1,100),index = [range(1,100)])

1      1
2      2
3      3
4      4
5      5
      ..
95    95
96    96
97    97
98    98
99    99
Length: 99, dtype: int64

In [96]:
pd.Series([1,3,45,66], index = [1,2,3,4])

1     1
2     3
3    45
4    66
dtype: int64

In [98]:
pd.Series([1,3,45,66], index = ['Jay','Mayur','Shriya','Shaival'])

Jay         1
Mayur       3
Shriya     45
Shaival    66
dtype: int64

In [139]:
v = np.array([116,45,78])
v

array([116,  45,  78])

In [101]:
type(v)

numpy.ndarray

In [102]:
v.shape

(3,)

In [153]:
v = v.reshape(5,1)
v

array([[116],
       [ 45],
       [ 78],
       [ 34],
       [ 34]])

In [148]:
v = np.append(v,34)
v

array([116,  45,  78,  34,  34])

In [160]:
v.T

array([[ 0, 45, 78, 34, 34]])

In [161]:
v2 = np.array([116,  5,  78,  4,  3])

In [178]:
v = np.array([116,  5,  78,  4,  3])

array([116,   5,  78,   4,   3])

In [184]:
v * v2

array([13456,    25,  6084,    16,     9])

In [1]:
# List Comprehension

In [6]:
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [15]:
[i if i%2 == 0 else "Odd" for i in range(20) ]

[0,
 'Odd',
 2,
 'Odd',
 4,
 'Odd',
 6,
 'Odd',
 8,
 'Odd',
 10,
 'Odd',
 12,
 'Odd',
 14,
 'Odd',
 16,
 'Odd',
 18,
 'Odd']

In [17]:
[[i,j] if j%2 == 0 else [i,'Not even'] for i in range(3) for j in range(10)]

[[0, 0],
 [0, 'Not even'],
 [0, 2],
 [0, 'Not even'],
 [0, 4],
 [0, 'Not even'],
 [0, 6],
 [0, 'Not even'],
 [0, 8],
 [0, 'Not even'],
 [1, 0],
 [1, 'Not even'],
 [1, 2],
 [1, 'Not even'],
 [1, 4],
 [1, 'Not even'],
 [1, 6],
 [1, 'Not even'],
 [1, 8],
 [1, 'Not even'],
 [2, 0],
 [2, 'Not even'],
 [2, 2],
 [2, 'Not even'],
 [2, 4],
 [2, 'Not even'],
 [2, 6],
 [2, 'Not even'],
 [2, 8],
 [2, 'Not even']]

In [18]:
# Lambda function

In [19]:
(lambda x: x**3)(3)

27

In [35]:
area = lambda x,y: x + y(x)

In [37]:
area(23, lambda x: x + 11)

57